config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :firms

  resources :services, only: [:index, :show, :new, :create, :edit, :update]

  resources :patients, only: [:index, :show, :new, :create, :edit, :update] do
    get 'patients/:id/events', to: 'patients#events', as: :patient_events
  end

  resources :ordonnances, only: [:new, :create, :edit, :update, :show]

  resources :prescripteurs, only: [:index, :new, :create, :edit, :update]

  resources :users, only: [:index, :edit, :update]

  resources :therapists do
    resources :services, only: [:index], defaults: { format: :json } do
      resources :time_slots, only: [:index], controller: 'time_slots'
    end
    get 'all_events', on: :member, defaults: { format: :json }
    member do
      patch :update_event
    end
  end

  resources :week_availabilities do
    resources :time_blocks
  end

  resources :event_individuels, only: [:new, :create]
  resources :event_individuels do
    member do
      patch :update_status
      patch :associate_ordonnance
    end
  end

end

app/models/firm.rb
class Firm < ApplicationRecord
  has_many :therapists

  validates :name, presence: true
end

app/controllers/firms_controller.rb
class FirmsController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_policy_scoped, only: :index
  before_action :set_firm, only: [:show, :edit, :update, :destroy]


  def index
    @firms = policy_scope(Firm)
  end

  def show
    authorize @firm
  end

  def new
    @firm = Firm.new
    authorize @firm
  end

  def create
    @firm = Firm.new(firm_params)
    authorize @firm

    if @firm.save
      redirect_to firms_path, notice: 'Firm was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    authorize @firm
    if @firm.update(firm_params)
      redirect_to firms_path, notice: 'La société a été mise à jour avec succès.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @firm
    @firm.therapists.update_all(firm_id: nil)
    if @firm.destroy
      redirect_to firms_url, notice: 'Firm was successfully destroyed.'
    else
      redirect_to firms_url, alert: 'Firm could not be destroyed. Please make sure all dependencies are removed.'
    end
  end

  private
  def firm_params
    params.require(:firm).permit(:name, :address, therapist_ids: [])
  end

  def set_firm
    @firm = Firm.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to firms_url, alert: 'Firm not found.'
  end
end

app/views/firms/_firms_list.html.erb
<!-- app/views/firms/_firms_list.html.erb -->

<% firms.each do |firm| %>
  <div class="card mb-4" data-controller="edit-form">
    <div class="card-body">
      <%= form_with(model: firm, local: true) do |f| %>

        <div class="form-header">
          <h3><%=firm.name%></h3>
          <div>
            <i class="fas fa-edit edit-icon" data-action="click->edit-form#edit"></i>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="form-group flex-group">
              <%= f.label :name, 'Nom : ' %>
              <%= f.text_field :name,
                              readonly: true,
                              class: "form-control",
                              data: { edit_form_target: "input" } %>
            </div>
            <div class="form-group flex-group">
              <%= f.label :address, 'Adresse : ' %>
              <%= f.text_area :address,
                              readonly: true,
                              class: "form-control",
                              rows: 2,
                              data: { edit_form_target: "textArea" } %>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :therapist_ids, 'Therapeutes associés' %>
              <%= f.collection_select :therapist_ids,
                                      Therapist.all,
                                      :id,
                                      :display_name,
                                      {},
                                      { multiple: true, class: "form-select", data: { edit_form_target: "select" }, disabled: true } %>
            </div>
          </div>
        </div>

        <div class="row">
          <div>
            <!-- <%= button_tag 'Edit', type: 'button', class: "editButton btn btn-outline-primary", data: { action: "click->edit-form#edit" } %> -->
            <%= f.submit "Save", class: "saveButton btn btn-outline-success d-none", data: { action: "click->edit-form#save" } %>
          </div>
        </div>

        <%= link_to "Supprimer", firm_path(firm), method: :delete, class: "btn btn-outline-danger", data: { turbo_confirm: "Êtes-vous sûr ?", action: "click->edit-form#confirmDelete" } %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/firms/index.html.erb
<!-- app/views/firms/index.html.erb -->
<div class="container" data-controller="edit-form">
  <h1 style="padding-top: 120px;">Sociétés</h1>
  <!-- Lien pour créer une nouvelle société -->
  <%= link_to 'Nouvelle Société', new_firm_path, class: "btn btn-primary mb-3" %>

  <%= render 'firms_list', firms: @firms %>
</div>

app/views/firms/new.html.erb
<!-- app/views/firms/new.html.erb -->
<div class="container mt-5">
  <h1 class="mb-4">New Firm</h1>

  <%= form_with model: @firm, local: true do |f| %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="field">
      <%= f.label :address %>
      <%= f.text_area :address, class: 'form-control' %>
    </div>

    <div class="field">
      <%= f.label :therapist_ids, "Select Therapists" %>
      <%= f.collection_select :therapist_ids, Therapist.all, :id, :display_name, { include_blank: true }, { multiple: true, class: 'form-control' } %>
    </div>

    <div class="actions">
      <%= f.submit 'Create Firm', class: 'btn btn-primary' %>
    </div>
  <% end %>
    <%= link_to 'Retour à la liste des sociétés', firms_path, class: 'btn btn-secondary mt-3' %>
</div>

app/views/firms/show.html.erb
<!-- app/views/firms/show.html.erb -->
<div class="container mt-5">
  <h1><%= @firm.name %></h1>
  <p><%= @firm.address %></p>
  <!-- Plus de détails sur la firme ici -->
</div>