config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :firms

  resources :services, only: [:index, :show, :new, :create, :edit, :update]

  resources :patients, only: [:index, :show, :new, :create, :edit, :update] do
    get 'patients/:id/events', to: 'patients#events', as: :patient_events
  end

  resources :ordonnances, only: [:new, :create, :edit, :update, :show]

  resources :prescripteurs, only: [:index, :new, :create, :edit, :update]

  resources :users, only: [:index, :edit, :update]

  resources :therapists do
    resources :services, only: [:index], defaults: { format: :json } do
      resources :time_slots, only: [:index], controller: 'time_slots'
    end
    get 'all_events', on: :member, defaults: { format: :json }
    member do
      patch :update_event
    end
  end

  resources :week_availabilities do
    resources :time_blocks
  end

  resources :event_individuels, only: [:new, :create]
  resources :event_individuels do
    member do
      patch :update_status
      patch :associate_ordonnance
    end
  end

end

app/models/week_availability.rb
class WeekAvailability < ApplicationRecord
  has_many :time_blocks, dependent: :destroy
  belongs_to :therapist

  validates :valid_from, presence: true
  validates :valid_until, presence: true
  validate :valid_until_after_valid_from

  private

  def valid_until_after_valid_from
    return if valid_until.blank? || valid_from.blank?

    if valid_until <= valid_from
      errors.add(:valid_until, "must be after the valid from date")
    end
  end
end

app/controllers/week_availabilities_controller.rb
class WeekAvailabilitiesController < ApplicationController

  before_action :authenticate_user!

  def index
    @week_availabilities = policy_scope(WeekAvailability)
                              .joins(:therapist)
                              .order('therapists.first_name ASC')
  end

  def new
    @week_availability = WeekAvailability.new
    authorize @week_availability
  end

  def show
    @week_availability = WeekAvailability.find(params[:id])
    authorize @week_availability
    redirect_to week_availabilities_path
  end

  def create
    @week_availability = WeekAvailability.new(week_availability_params)
    @week_availability.therapist = current_user.therapist
    authorize @week_availability

    if @week_availability.save
      redirect_to week_availabilities_path, notice: 'Week Availability was successfully created.'
    else
      flash[:alert] = @week_availability.errors.full_messages.join(", ")
      redirect_to week_availabilities_path
    end
  end

  def destroy
    @week_availability = WeekAvailability.find(params[:id])
    authorize @week_availability
    @week_availability.destroy
    redirect_to week_availabilities_path, notice: 'Week Availability was successfully deleted.', status: :found
  end

  def edit
    @week_availability = WeekAvailability.find(params[:id])
    authorize @week_availability
  end

  def update
    @week_availability = WeekAvailability.find(params[:id])
    authorize @week_availability

    if @week_availability.update(week_availability_params)
      redirect_to week_availabilities_path, notice: 'Week Availability was successfully updated.'
    else
      flash[:alert] = @week_availability.errors.full_messages.join(", ")
      redirect_to week_availabilities_path
    end
  end

  private

  def week_availability_params
    params.require(:week_availability).permit(:valid_from, :valid_until, :name)
  end

end

app/views/week_availabilities/_week_availability_form.html.erb
<%# app/views/week_availabilities/_week_availability_form.html.erb %>

<div class="card mb-4" data-controller="edit-form">

  <%= form_with(model: week_availability, local: true, html: { class: "edit-form" }) do |f| %>
    <div class="row">
      <!-- Fields for WeekAvailability -->
      <div class="col-md-2">
        <h2><%= week_availability.therapist.first_name %> <%= week_availability.therapist.last_name.upcase %></h2>
        <div class="form-group">
          <%= f.label :valid_from, 'Valid From: ' %>
          <%= f.date_field :valid_from, class: 'form-control', readonly: true %>
        </div>
        <div class="form-group">
          <%= f.label :valid_until, 'Valid Until: ' %>
          <%= f.date_field :valid_until, class: 'form-control', readonly: true %>
        </div>
      </div>
      <div class="col-md-10">
        <!-- Table for Time Blocks -->
        <div data-toggle-target="content">
          <table class="table table-transparent" style="height: 500px;">
            <thead>
              <tr>
                <% @days = ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"] %>
                <% @days.each do |day| %>
                  <th style="width: 14.28%;"><%= day %></th>
                <% end %>
              </tr>
            </thead>
            <tbody>
              <tr>
                <% @days.each do |day| %>
                  <td>
                    <% time_blocks_for_day = week_availability.time_blocks.where(week_day: day) %>
                    <% time_blocks_for_day.each do |time_block| %>
                      <div class="time-block-card" style="position: relative; height: <%= height_percentage(time_block.start_time, time_block.end_time) %>%; top: <%= top_position(time_block.start_time) %>%;">
                        <%= form_with(model: [week_availability, time_block], local: true, html: { class: "time-block-edit-form" }) do |tb_form| %>
                          <div>
                            <%= tb_form.time_field :start_time, class: 'form-control' %>
                            <%= tb_form.time_field :end_time, class: 'form-control' %>
                            <%= tb_form.collection_select :room_id, Room.all, :id, :name, {}, {class: 'form-control'} %>
                          </div>
                          <div>
                            <%= tb_form.submit "Update", class: "btn btn-primary" %>
                            <%= link_to "Cancel", week_availabilities_path, class: "btn btn-secondary" %>
                            <%= link_to week_availability_time_block_path(week_availability, time_block), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'btn btn-danger' do %>
                              <i class="fas fa-trash-alt" title="Supprimer"></i>
                            <% end %>
                          </div>
                        <% end %>
                      </div>
                    <% end %>
                  </td>
                <% end %>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div class="col-md-1">
        <div class="form-header">
          <i class="fas fa-edit edit-icon" data-action="click->edit-form#edit"></i>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3">
        <%= f.submit "Save", class: "saveButton btn btn-dark d-none" %>
      </div>
    </div>
  <% end %>

</div>

app/views/week_availabilities/index.html.erb
<!-- app/views/week_availabilities/index.html.erb -->

<div class="container">
  <h1 style="margin-top: 120px;">Week Availabilities</h1>

  <% if @week_availabilities.any? %>
    <ul>
      <% @week_availabilities.each do |week_availability| %>
        <%= render 'week_availability_form', week_availability: week_availability %>
      <% end %>
    </ul>
  <% else %>
    <p>No week availabilities available.</p>
  <% end %>
</div>



<!--
<div class="container">
  <div style="margin-top: 120px">
    <div class="mb-5">
      <div class="row">
        <h1> Gestion des disponibilitées </h1>
        <%= t('hello') %>
    </div>
    <div class="mb-5">
      <div data-controller="toggle">
        <% @week_availabilities.each do |week_availability| %>
          <div class="mb-5">
            <div class="text-center">
              <%= week_availability.therapist.first_name %> <%= week_availability.therapist.last_name.upcase %>
              De <strong><%= l(week_availability.valid_from, format: :long) %></strong> à <strong><%= l(week_availability.valid_until, format: :long) %></strong>
              <%= link_to new_week_availability_time_block_path(week_availability), class: 'float-right ml-2' do %>
                  <i class="fas fas-black fa-plus" title="Add Time Block"></i>
              <% end %>
              <%= link_to edit_week_availability_path(week_availability), class: 'float-right ml-2' do %>
                <i class="fas fas-black fa-edit" title="Edit"></i>
              <% end %>
              <%= link_to week_availability_path(week_availability), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'float-right ml-2' do %>
                <i class="fas fas-black fa-trash-alt" title="Delete"></i>
              <% end %>
              <button data-action="toggle#toggle" class="btn btn-sm float-right">
                <i class="fas fas-black fa-eye" data-toggle-icon></i>
              </button>
            </div>
            <div data-toggle-target="content">
              <table class="table table-transparent" style="height: 500px;">
                <thead>
                  <tr>
                    <% @days = ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"] %>
                    <% @days.each do |day| %>
                      <th style="width: 14.28%;"><%= day %></th>
                    <% end %>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <% @days.each do |day| %>
                      <td>
                        <% time_blocks_for_day = week_availability.time_blocks.where(week_day: day) %>
                        <% time_blocks_for_day.each do |time_block| %>
                          <div class="time-block-card" style="height: <%= height_percentage(time_block.start_time, time_block.end_time) %>%; top: <%= top_position(time_block.start_time) %>%;">
                              <div>
                                  <p>
                                      <strong><%= "#{time_block.start_time.strftime('%H:%M')} to #{time_block.end_time.strftime('%H:%M')}" %></strong>
                                      <br>
                                      <%= time_block.room.name %>
                                      <br>
                                      <%= link_to edit_week_availability_time_block_path(week_availability, time_block) do %>
                                          <i class="fas fas-black fa-edit" title="Edit"></i>
                                      <% end %>
                                      <%= link_to week_availability_time_block_path(week_availability, time_block), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                                          <i class="fas fas-black fa-trash-alt" title="Delete"></i>
                                      <% end %>
                                  </p>
                              </div>
                          </div>
                        <% end %>
                      </td>
                    <% end %>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        <% end %>
      </div>
  </div>
</div>
-->

app/views/week_availabilities/new.html.erb
<div class="container">
  <div style="margin-top: 120px" class="row mt-5">
    <div class="col-md-6 offset-md-3">
      <div class="p-4 shadow-rounded">
        <h2 class="text-center">New Week Availability</h2>

        <%= form_for(@week_availability) do |f| %>
          <% if @week_availability.errors.any? %>
            <div class="alert alert-danger">
              <h4><%= pluralize(@week_availability.errors.count, "error") %> prohibited this week availability from being saved:</h4>
              <ul>
                <% @week_availability.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>

          <div class="form-group">
            <%= f.label :valid_from %>
            <%= f.date_field :valid_from, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :valid_until %>
            <%= f.date_field :valid_until, class: 'form-control' %>
          </div>

          <div class="actions mt-3">
            <%= f.submit 'Create Week Availability', class: 'btn btn-primary' %>
            <%= link_to 'Cancel', week_availabilities_path, class: 'btn btn-outline-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>