config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :firms

  resources :services, only: [:index, :show, :new, :create, :edit, :update]

  resources :patients, only: [:index, :show, :new, :create, :edit, :update] do
    get 'patients/:id/events', to: 'patients#events', as: :patient_events
  end

  resources :ordonnances, only: [:new, :create, :edit, :update, :show]

  resources :prescripteurs, only: [:index, :new, :create, :edit, :update]

  resources :users, only: [:index, :edit, :update]

  resources :therapists do
    resources :services, only: [:index], defaults: { format: :json } do
      resources :time_slots, only: [:index], controller: 'time_slots'
    end
    get 'all_events', on: :member, defaults: { format: :json }
    member do
      patch :update_event
    end
  end

  resources :week_availabilities do
    resources :time_blocks
  end

  resources :event_individuels, only: [:new, :create]
  resources :event_individuels do
    member do
      patch :update_status
      patch :associate_ordonnance
    end
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "Logo-50x50.jpg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

          <li class="nav-item active">
            <%= link_to "Acceuil", "/", class: "nav-link" %>
          </li>

        <% if user_signed_in? %> <!-- Si l'utilisateur est connecté -->

          <% if current_user.is_admin? %> <!-- Si l'utilisateur est admin -->
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownAdmin" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Admin
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownAdmin">
                <%= link_to "Utilisateurs", users_path, class: "dropdown-item" %>
                <%= link_to "Sociétés", firms_path, class: "dropdown-item" %>
                <%= link_to "Thérapeutes", therapists_path, class: "dropdown-item" %>
                <%= link_to "Services", services_path, class: "dropdown-item" %>
                <%= link_to "Disponibilités", week_availabilities_path, class: "dropdown-item" %>
                <!-- Ajoutez d'autres liens admin si nécessaire -->
              </div>
            </li>
          <% end %>

          <% if user_signed_in? && (current_user.is_admin? || current_user.therapist?) %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownTherapists" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Thérapeutes
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownTherapists">
                <% Therapist.all.each do |therapist| %>
                  <%= link_to therapist.first_name, therapist_path(therapist), class: "dropdown-item" %>
                <% end %>
              </div>
            </li>

            <li class="nav-item">
              <%= link_to "Patients", patients_path, class: "nav-link" %>
            </li>

            <li class="nav-item">
              <%= link_to "Prescripteurs", prescripteurs_path, class: "nav-link" %>
            </li>
          <% end %>

          <% if user_signed_in? && (current_user.is_admin? || current_user.therapist? || current_user.patient?) %>
            <li class="nav-item">
              <%= link_to "Nouveaux rendez-vous", new_event_individuel_path, class: "nav-link" %>
            </li>
          <% end %>


          <li class="nav-item dropdown">

            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <!-- <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %> -->
            </a>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>

      </ul>
    </div>

  </div>
</div>