config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :firms

  resources :services, only: [:index, :show, :new, :create, :edit, :update]

  resources :patients, only: [:index, :show, :new, :create, :edit, :update] do
    get 'patients/:id/events', to: 'patients#events', as: :patient_events
  end

  resources :ordonnances, only: [:new, :create, :edit, :update, :show]

  resources :prescripteurs, only: [:index, :new, :create, :edit, :update]

  resources :users, only: [:index, :edit, :update]

  resources :therapists do
    resources :services, only: [:index], defaults: { format: :json } do
      resources :time_slots, only: [:index], controller: 'time_slots'
    end
    get 'all_events', on: :member, defaults: { format: :json }
    member do
      patch :update_event
    end
  end

  resources :week_availabilities do
    resources :time_blocks
  end

  resources :event_individuels, only: [:new, :create]
  resources :event_individuels do
    member do
      patch :update_status
      patch :associate_ordonnance
    end
  end

end

app/models/prescripteur.rb
class Prescripteur < ApplicationRecord
  has_many :ordonnances

  validates :name, presence: true
end

app/controllers/prescripteurs_controller.rb
class PrescripteursController < ApplicationController
  before_action :authenticate_user!
  before_action :set_prescripteur, only: [:edit, :update]
  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  def index
    if params[:search].present?
      search_query = "%#{params[:search]}%"
      @prescripteurs = policy_scope(Prescripteur).includes(:ordonnances).order(:name).where("name ILIKE ?", search_query)
    else
      @prescripteurs = policy_scope(Prescripteur).includes(:ordonnances).order(:name)
    end
  end

  def new
    @prescripteur = Prescripteur.new
    authorize @prescripteur
  end

  def create
    @prescripteur = Prescripteur.new(prescripteur_params)
    authorize @prescripteur
    if @prescripteur.save
      redirect_to prescripteurs_path, notice: 'Le prescripteur a été créé.'
    else
      render :new
    end
  end

  def edit
    authorize @prescripteur
  end

  def update
    authorize @prescripteur
    if @prescripteur.update(prescripteur_params)
      redirect_to prescripteurs_path, notice: 'Le prescripteur a été mis à jour.'
    else
      render :edit
    end
  end

  private

  def set_prescripteur
    @prescripteur = Prescripteur.find(params[:id])
  end

  def prescripteur_params
    params.require(:prescripteur).permit(:name, :address, :tel, :mail)
  end

end

app/views/prescripteurs/_prescripteurs_form.html.erb
<%# app/views/prescripteurs/_prescripteurs_form.html.erb %>

<div class="card mb-4" data-controller="edit-form">

  <%= form_with(model: prescripteur, local: true, html: { class: "edit-form" }) do |f| %>


    <div class="row">
      <!-- Les champs du prescripteur -->
      <div class="col-md-3">
        <div class="form-group flex-group">
          <%= f.label :name, 'Nom : ' %>
          <%= f.text_field :name, class: 'form-control', readonly: true %>
        </div>
        <div class="form-group flex-group">
          <%= f.label :tel, 'Téléphone : ' %>
          <%= f.text_field :tel, class: 'form-control', readonly: true %>
        </div>
      </div>
      <div class="col-md-8">
          <div class="form-group flex-group">
            <%= f.label :address, 'Adresse : ' %>
            <%= f.text_field :address, class: 'form-control', readonly: true %>
          </div>
          <div class="form-group flex-group">
            <%= f.label :mail, 'E-mail : ' %>
            <%= f.email_field :mail, class: 'form-control', readonly: true %>
          </div>
          <div class="form-group">
            <% prescripteur.ordonnances.group_by(&:patient).each do |patient, ordonnances| %>
                <%= link_to "#{patient.first_name.capitalize} #{patient.last_name.upcase} (#{ordonnances.count})", patient_path(patient) %>
            <% end %>
          </div>
      </div>


      <div class="col-md-1">
        <div class="form-header">
          <div>
            <i class="fas fa-edit edit-icon" data-action="click->edit-form#edit"></i>
          </div>
        </div>
      </div>
      <!-- Plus de champs selon les attributs de votre modèle Prescripteur -->
    </div>

    <div class="row">
      <div class="col-md-3">
        <%= f.submit "Save", class: "saveButton btn btn-dark d-none" %>
      </div>
    </div>
  <% end %>

</div>

app/views/prescripteurs/index.html.erb
<!-- app/views/prescripteurs/index.html.erb -->

<div class="container">
  <h1 style="margin-top: 120px;">Prescripteurs</h1>
  <%= link_to 'Nouveau Prescripteur', new_prescripteur_path, class: "btn btn-primary" %>

  <%= form_with(url: prescripteurs_path, method: :get, local: true) do |f| %>
    <%= f.text_field :search, placeholder: "Rechercher un prescripteur..." %>
    <%= f.submit "Rechercher" %>
  <% end %>

  <% if @prescripteurs.any? %>
    <ul>
      <% @prescripteurs.each do |prescripteur| %>
        <%= render 'prescripteurs_form', prescripteur: prescripteur %>
      <% end %>
    </ul>
  <% else %>
    <p>Pas de prescripteurs disponibles.</p>
  <% end %>
</div>


</div>

app/views/prescripteurs/new.html.erb
<%# app/views/prescripteurs/new.html.erb %>

<div class="container">

  <h1 style="margin-top: 120px;">Nouveau Prescripteur</h1>

  <%= form_with(model: @prescripteur, local: true) do |f| %>
    <div class="form-group">
      <%= f.label :name, 'Nom : ' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <%= f.submit "Créer Prescripteur", class: "btn btn-primary" %>
  <% end %>

</div>